In [1]:
import os
os.chdir("..") # Ek folder piche jane ke liye
print(os.getcwd()) # Check karein ke ab path 'psl_ai_platform' par hai ya nahi

c:\Users\User\Desktop\psl_ai_platform

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
file_path = Path("data/processed/ball_by_ball/psl_ball_by_ball_clean.csv")
df = pd.read_csv(file_path)
df.head()

,match_id,innings_number,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,...,fielders_involved,match_date,city,venue,team1,team2,toss_winner,toss_decision,phase,ball_id
0,959175,1,Islamabad United,0,1,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.1
1,959175,1,Islamabad United,0,2,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.2
2,959175,1,Islamabad United,0,3,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.3
3,959175,1,Islamabad United,0,4,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.4
4,959175,1,Islamabad United,0,5,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.5

In [4]:
df.shape

(78660, 25)

In [5]:
df.dtypes

match_id               int64
innings_number         int64
batting_team          object
over                   int64
ball                   int64
batter               float64
bowler                object
non_striker           object
runs_batter            int64
runs_extras            int64
runs_total             int64
extras_type           object
wicket                 int64
wicket_type          float64
player_out           float64
fielders_involved    float64
match_date            object
city                  object
venue                 object
team1                 object
team2                 object
toss_winner           object
toss_decision         object
phase                 object
ball_id              float64
dtype: object

In [6]:
df.isna().sum().sort_values(ascending=False).head(20)

player_out           78660
batter               78660
fielders_involved    78660
wicket_type          78660
extras_type          74379
city                  9887
match_id                 0
phase                    0
toss_decision            0
toss_winner              0
team2                    0
team1                    0
venue                    0
match_date               0
wicket                   0
innings_number           0
runs_total               0
runs_extras              0
runs_batter              0
non_striker              0
dtype: int64

In [7]:
df["phase"].value_counts(dropna=False)

phase
middle       36421
powerplay    24968
death        17271
Name: count, dtype: int64

In [8]:
df[["match_id", "innings_number", "over", "ball", "ball_id", "batter", "bowler", "runs_total"]].head(20)

,match_id,innings_number,over,ball,ball_id,batter,bowler,runs_total
0,959175,1,0,1,0.1,NaN,Anwar Ali,0
1,959175,1,0,2,0.2,NaN,Anwar Ali,0
2,959175,1,0,3,0.3,NaN,Anwar Ali,0
3,959175,1,0,4,0.4,NaN,Anwar Ali,0
4,959175,1,0,5,0.5,NaN,Anwar Ali,0
5,959175,1,0,6,0.6,NaN,Anwar Ali,0
6,959175,1,1,1,1.1,NaN,Zulfiqar Babar,0
7,959175,1,1,2,1.2,NaN,Zulfiqar Babar,1
8,959175,1,1,3,1.3,NaN,Zulfiqar Babar,2
9,959175,1,1,4,1.4,NaN,Zulfiqar Babar,0
10,959175,1,1,5,1.5,NaN,Zulfiqar Babar,0
11,959175,1,1,6,1.6,NaN,Zulfiqar Babar,2
12,959175,1,2,1,2.1,NaN,Anwar Ali,1
13,959175,1,2,2,2.2,NaN,Anwar Ali,4
14,959175,1,2,3,2.3,NaN,Anwar Ali,0
15,959175,1,2,4,2.4,NaN,Anwar Ali,0
16,959175,1,2,5,2.5,NaN,Anwar Ali,0
17,959175,1,2,6,2.6,NaN,Anwar Ali,1
18,959175,1,3,1,3.1,NaN,Mohammad Nabi,0
19,959175,1,3,2,3.2,NaN,Mohammad Nabi,0