In [1]:
import os
os.chdir("..") # Ek folder piche jane ke liye
print(os.getcwd()) # Check karein ke ab path 'psl_ai_platform' par hai ya nahi

c:\Users\User\Desktop\psl_ai_platform

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
file_path = Path("data/processed/player_data/player_profile_master.csv")
df = pd.read_csv(file_path)
df.head()

,player_name,source,first_seen_match_id,last_seen_match_id,notes_x,batting_balls_faced,batting_runs_scored,batting_total_runs,batting_dismissals,batting_matches_played,...,bowling_matches_played,bowling_overs,bowling_economy,batting_hand,bowling_style,player_role,country,is_overseas,date_of_birth,notes_y
0,A Lyth,cricsheet_parsed,1211672,1211675,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.17,8.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A Zampa,cricsheet_parsed,1527553,1527571,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,20.17,7.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AB de Villiers,cricsheet_parsed,1168820,1168839,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD Hales,cricsheet_parsed,1128842,1475268,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD Russell,cricsheet_parsed,959175,1168829,NaN,NaN,NaN,NaN,NaN,NaN,...,17.0,56.83,8.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(447, 25)

In [5]:
df.columns.tolist()

['player_name',
 'source',
 'first_seen_match_id',
 'last_seen_match_id',
 'notes_x',
 'batting_balls_faced',
 'batting_runs_scored',
 'batting_total_runs',
 'batting_dismissals',
 'batting_matches_played',
 'batting_strike_rate',
 'batting_average',
 'bowling_balls',
 'bowling_runs_conceded',
 'bowling_wickets',
 'bowling_matches_played',
 'bowling_overs',
 'bowling_economy',
 'batting_hand',
 'bowling_style',
 'player_role',
 'country',
 'is_overseas',
 'date_of_birth',
 'notes_y']

In [6]:
df.isna().sum().sort_values(ascending=False)

date_of_birth             447
notes_x                   447
batting_balls_faced       447
batting_runs_scored       447
batting_total_runs        447
batting_dismissals        447
batting_matches_played    447
batting_strike_rate       447
batting_average           447
bowling_style             445
notes_y                   444
is_overseas               444
country                   444
player_role               444
batting_hand              444
bowling_economy           155
bowling_balls             155
bowling_overs             155
bowling_matches_played    155
bowling_wickets           155
bowling_runs_conceded     155
source                      0
last_seen_match_id          0
first_seen_match_id         0
player_name                 0
dtype: int64

In [7]:
df[["player_name", "batting_runs_scored", "batting_strike_rate", "bowling_wickets", "bowling_economy"]].head(20)

,player_name,batting_runs_scored,batting_strike_rate,bowling_wickets,bowling_economy
0,A Lyth,NaN,NaN,0.0,8.20
1,A Zampa,NaN,NaN,0.0,7.24
2,AB de Villiers,NaN,NaN,NaN,NaN
3,AD Hales,NaN,NaN,NaN,NaN
4,AD Russell,NaN,NaN,0.0,8.69
5,ADS Fletcher,NaN,NaN,NaN,NaN
6,AF Milne,NaN,NaN,0.0,10.82
7,AGS Gous,NaN,NaN,NaN,NaN
8,AJ Hosein,NaN,NaN,0.0,8.04
9,AJ Turner,NaN,NaN,0.0,6.83
10,AJ Tye,NaN,NaN,0.0,10.70
11,AM Hardie,NaN,NaN,0.0,12.33
12,AM Rossington,NaN,NaN,NaN,NaN
13,AP Devcich,NaN,NaN,0.0,13.73
14,AS Joseph,NaN,NaN,0.0,9.01
15,AW Summers,NaN,NaN,0.0,7.15
16,Aamer Azmat,NaN,NaN,0.0,2.56
17,Aamer Jamal,NaN,NaN,0.0,9.77
18,Aamer Yamin,NaN,NaN,0.0,8.67
19,Abbas Afridi,NaN,NaN,0.0,9.32