In [1]:
import os
os.chdir("..") # Ek folder piche jane ke liye
print(os.getcwd()) # Check karein ke ab path 'psl_ai_platform' par hai ya nahi

c:\Users\User\Desktop\psl_ai_platform

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
ball_file = Path("data/processed/ball_by_ball/psl_ball_by_ball_clean.csv")
player_file = Path("data/processed/player_data/player_profile_master.csv")

ball_df = pd.read_csv(ball_file)
player_df = pd.read_csv(player_file)

In [4]:
ball_df.shape, player_df.shape

((78660, 25), (447, 25))

In [5]:
ball_df.head()

,match_id,innings_number,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,...,fielders_involved,match_date,city,venue,team1,team2,toss_winner,toss_decision,phase,ball_id
0,959175,1,Islamabad United,0,1,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.1
1,959175,1,Islamabad United,0,2,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.2
2,959175,1,Islamabad United,0,3,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.3
3,959175,1,Islamabad United,0,4,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.4
4,959175,1,Islamabad United,0,5,NaN,Anwar Ali,Sharjeel Khan,0,0,...,NaN,2016-02-04,NaN,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators,Quetta Gladiators,field,powerplay,0.5

In [6]:
player_df.head()

,player_name,source,first_seen_match_id,last_seen_match_id,notes_x,batting_balls_faced,batting_runs_scored,batting_total_runs,batting_dismissals,batting_matches_played,...,bowling_matches_played,bowling_overs,bowling_economy,batting_hand,bowling_style,player_role,country,is_overseas,date_of_birth,notes_y
0,A Lyth,cricsheet_parsed,1211672,1211675,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.17,8.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A Zampa,cricsheet_parsed,1527553,1527571,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,20.17,7.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AB de Villiers,cricsheet_parsed,1168820,1168839,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD Hales,cricsheet_parsed,1128842,1475268,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD Russell,cricsheet_parsed,959175,1168829,NaN,NaN,NaN,NaN,NaN,NaN,...,17.0,56.83,8.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
ball_df.describe(include="all")

,match_id,innings_number,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,...,fielders_involved,match_date,city,venue,team1,team2,toss_winner,toss_decision,phase,ball_id
count,7.866000e+04,78660.000000,78660,78660.000000,78660.000000,0.0,78660,78660,78660.0,78660.000000,...,0.0,78660,68773,78660,78660,78660,78660,78660,78660,78660.000000
unique,NaN,NaN,8,NaN,NaN,NaN,292,404,NaN,NaN,...,NaN,260,7,10,8,8,8,2,3,NaN
top,NaN,NaN,Peshawar Zalmi,NaN,NaN,NaN,Hasan Ali,Babar Azam,NaN,NaN,...,NaN,2024-02-18,Karachi,"Gaddafi Stadium, Lahore",Lahore Qalandars,Quetta Gladiators,Peshawar Zalmi,field,middle,NaN
freq,NaN,NaN,13956,NaN,NaN,NaN,2239,3434,NaN,NaN,...,NaN,509,19831,15303,15647,17255,15453,58942,36421,NaN
mean,1.265179e+06,1.481350,NaN,9.106827,3.617900,NaN,NaN,NaN,0.0,0.070277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.468579
std,1.541041e+05,0.502092,NaN,5.641341,1.811583,NaN,NaN,NaN,0.0,0.359776,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.644271
min,9.591750e+05,1.000000,NaN,0.000000,1.000000,NaN,NaN,NaN,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000
25%,1.168824e+06,1.000000,NaN,4.000000,2.000000,NaN,NaN,NaN,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000
50%,1.247034e+06,1.000000,NaN,9.000000,4.000000,NaN,NaN,NaN,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.400000
75%,1.416474e+06,2.000000,NaN,14.000000,5.000000,NaN,NaN,NaN,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.300000
max,1.527573e+06,4.000000,NaN,19.000000,11.000000,NaN,NaN,NaN,0.0,5.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.900000

In [8]:
ball_df[["match_id", "batter", "bowler", "runs_total", "wicket", "phase"]].head(20)

    match_id  batter          bowler  runs_total  wicket      phase
0     959175     NaN       Anwar Ali           0       0  powerplay
1     959175     NaN       Anwar Ali           0       0  powerplay
2     959175     NaN       Anwar Ali           0       0  powerplay
3     959175     NaN       Anwar Ali           0       0  powerplay
4     959175     NaN       Anwar Ali           0       0  powerplay
5     959175     NaN       Anwar Ali           0       0  powerplay
6     959175     NaN  Zulfiqar Babar           0       0  powerplay
7     959175     NaN  Zulfiqar Babar           1       0  powerplay
8     959175     NaN  Zulfiqar Babar           2       0  powerplay
9     959175     NaN  Zulfiqar Babar           0       0  powerplay
10    959175     NaN  Zulfiqar Babar           0       0  powerplay
11    959175     NaN  Zulfiqar Babar           2       0  powerplay
12    959175     NaN       Anwar Ali           1       0  powerplay
13    959175     NaN       Anwar Ali           4       0  powerplay
14    959175     NaN       Anwar Ali           0       0  powerplay
15    959175     NaN       Anwar Ali           0       0  powerplay
16    959175     NaN       Anwar Ali           0       0  powerplay
17    959175     NaN       Anwar Ali           1       0  powerplay
18    959175     NaN   Mohammad Nabi           0       0  powerplay
19    959175     NaN   Mohammad Nabi           0       0  powerplay

In [9]:
ball_df["phase"].value_counts(dropna=False)

phase
middle       36421
powerplay    24968
death        17271
Name: count, dtype: int64

In [10]:
ball_df["runs_total"].value_counts().sort_index()

runs_total
0    26776
1    32929
2     4891
3      197
4     9445
5      167
6     4227
7       28
Name: count, dtype: int64

In [11]:
ball_df.isna().sum().sort_values(ascending=False).head(20)

player_out           78660
batter               78660
fielders_involved    78660
wicket_type          78660
extras_type          74379
city                  9887
match_id                 0
phase                    0
toss_decision            0
toss_winner              0
team2                    0
team1                    0
venue                    0
match_date               0
wicket                   0
innings_number           0
runs_total               0
runs_extras              0
runs_batter              0
non_striker              0
dtype: int64

In [12]:
player_df.isna().sum().sort_values(ascending=False)

date_of_birth             447
notes_x                   447
batting_balls_faced       447
batting_runs_scored       447
batting_total_runs        447
batting_dismissals        447
batting_matches_played    447
batting_strike_rate       447
batting_average           447
bowling_style             445
notes_y                   444
is_overseas               444
country                   444
player_role               444
batting_hand              444
bowling_economy           155
bowling_balls             155
bowling_overs             155
bowling_matches_played    155
bowling_wickets           155
bowling_runs_conceded     155
source                      0
last_seen_match_id          0
first_seen_match_id         0
player_name                 0
dtype: int64